[package]
name = "littlefs2-sys"
description = "Low-level bindings to littlefs"
version = "0.1.6"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"
license = "BSD-3-Clause"
readme = "README.md"
categories = ["embedded", "filesystem", "no-std"]
repository = "https://github.com/nickray/littlefs2-sys"

[dependencies]
cty = "0.2.1"
log = "0.4.20"

[build-dependencies]
bindgen = { version = "0.65.1", default-features = false, features = [
    "runtime",
] }
cc = "1"

[features]
assertions = []
trace = []
